//
//  UID2GoogleAdapterErrors.swift
//  
//
//  Created by Brad Leege on 3/23/23.
//

import Foundation

/// Errors generated by Plugin
public enum UID2GoogleAdapterErrors: Error {
    
    /// Advertising Token Not Found for IMA Adapter
    case advertisingTokenNotFoundForIMA
    
}
