# Uncomment the next line to define a global platform for your project
platform :ios, '16.2'

target 'UID2IMAPluginDevelopmentApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UID2IMAPluginDevelopmentApp
  pod 'UID2-IMA-Plugin', :path => '../..'

end
