name: Test Pull Requests

on:
  pull_request:
    branches: [ main ]

  # this allows us to manually run this job
  workflow_dispatch:

jobs:
  swift-code-checks:
    name: Code Tests
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install swiftlint

      - name: Lint code
        run: swiftlint lint --config .swiftlint.yml --reporter github-actions-logging

      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Build
        run: xcodebuild -scheme UID2IMAPlugin -destination "generic/platform=iOS"

      - name: Run unit tests
        run: xcodebuild test -scheme UID2IMAPluginTests -sdk iphonesimulator17.4 -destination "OS=17.4,name=iPhone 15"

      - name: Lint pod spec
        run: pod lib lint --verbose

  vulnerability-scan:
      name: Vulnerability Scan
      runs-on: ubuntu-latest
      needs: [swift-code-checks]

      steps:
        - name: Vulnerability Scan
          uses: IABTechLab/uid2-shared-actions/actions/vulnerability_scan_filesystem@v2
